# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          - task: Bash@3
          displayName: Twistcli Scan
          inputs:
          targetType: inline
          script: 
            curl -k -O -u $(USER):$(PW) $(TL_CONSOLE)/api/v1/util/twistcli;
            chmod a+x twistcli;
            ./twistcli images scan --address $(TL_CONSOLE) -u $(USER) -p $(PW) --details $(containerRegistry)/ubuntu-latest:$(Build.BuildId);
            