on:  [push]
jobs:
  scan:
    name: Scan image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Prisma Cloud 
        id: scan
        uses: bridgecrewio/checkov-action@master 
        env:
          PRISMA_API_URL: https://api.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
